fix: bump nette/utils from 4.0.5 to 4.0.6 (#1319)
Bumps [nette/utils](https://github.com/nette/utils) from 4.0.5 to 4.0.6.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/nette/utils/releases">nette/utils's
releases</a>.</em></p>
<blockquote>
<h2>Released version 4.0.6</h2>
<ul>
<li>Image: catches all errors during saving</li>
<li>added Helpers::IsWindows</li>
<li>added ShouldNotHappenException</li>
<li>added <code>FileSystem::resolvePath()</code> <a
href="https://redirect.github.com/nette/utils/issues/308">#308</a></li>
<li>tests: improved descriptions</li>
<li>exception: use natural explanatory style</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/nette/utils/commit/ce708655043c7050eb050df361c5e313cf708309"><code>ce70865</code></a>
Image: catches all errors during saving</li>
<li><a
href="https://github.com/nette/utils/commit/574a2d1d7540b587ec9f8e877b6af46c0745ab0b"><code>574a2d1</code></a>
added Helpers::IsWindows</li>
<li><a
href="https://github.com/nette/utils/commit/f695262986cc82aff804f116622b3904318dbf32"><code>f695262</code></a>
added ShouldNotHappenException</li>
<li><a
href="https://github.com/nette/utils/commit/259c2bf462dbc333a67fb453378ae458a08e96ce"><code>259c2bf</code></a>
added FileSystem::resolvePath() [Closes <a
href="https://redirect.github.com/nette/utils/issues/308">#308</a>]</li>
<li><a
href="https://github.com/nette/utils/commit/13130bb9a3c28ddde8758cf4930c8d04a6f10c02"><code>13130bb</code></a>
tests: improved descriptions</li>
<li><a
href="https://github.com/nette/utils/commit/23a8ea7944eb1b7261ba63f974889ade71c64f68"><code>23a8ea7</code></a>
exception: use natural explanatory style</li>
<li><a
href="https://github.com/nette/utils/commit/2a404d47f343ca42de3870322a28fcd3e430ec79"><code>2a404d4</code></a>
typo</li>
<li><a
href="https://github.com/nette/utils/commit/17cf0486342c39e2ae91cb6d01735d87130a9924"><code>17cf048</code></a>
github actions updated</li>
<li>See full diff in <a
href="https://github.com/nette/utils/compare/v4.0.5...v4.0.6">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=nette/utils&package-manager=composer&previous-version=4.0.5&new-version=4.0.6)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>